### ISSUE TITLE
Question: wondering how it work?

### ISSUE THREAD

**Issue by YasminBZ** [gobinaris/faasmark#6]
Hello,
i'm using an open source serverless framework , so in this case if i want to benchmark and to do some performance tests, how could this tool be used in this case.

Thank you .

**Comment by avnerbraverman** [comment]
Faasmark uses Serverless Framework for testing AWS Lambda. Unfortunately, when Faasmark was built I couldn't get the framework to work with Azure or Google. Faasmark currently uses Google's own CLI to test their cloud. Azure testing requires deploying code manually through their web interface.

We'd appreciate PRs that would allow using Serverless Framework across cloud providers.
